app:
  name: truelogic
#localhost:8080/h2-console
spring:
  datasource:
    url: jdbc:h2:file:./test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
